#! /bin/bash

usage() {
  >&2 echo "usage: $0 <source image> <target device>"
}

if [ $# -ne 2 ]; then
  usage
  exit 2
fi

SOURCE_IMAGE="$1"
TARGET_DEVICE="$2"

if [ ! -f "${SOURCE_IMAGE}" ]; then
  >&2 echo "Source image is not a regular file."
  exit 10
fi

if [ ! $(head -c 8 "${SOURCE_IMAGE}") == "ALDIMAGE" ]; then
  >&2 echo "Source image does not have ALDIMAGE signature."
  exit 11
fi

if [ ! -b "${TARGET_DEVICE}" ]; then
  >&2 echo "Target device is not a block device."
  exit 12
fi

if [ ! -w "${TARGET_DEVICE}" ]; then
  >&2 echo "Target device is not writable."
  exit 13
fi

DEVICE_TYPE=$(lsblk "${TARGET_DEVICE}" -ndo TYPE)
if [ "${DEVICE_TYPE}" != "disk" ]; then
  >&2 echo "Target device is not a disk."
  exit 14
fi

DEVICE_SIZE=$(lsblk "${TARGET_DEVICE}" -ndbo SIZE)
IMAGE_SIZE=$(stat -c%s "${SOURCE_IMAGE}")
if [ "${DEVICE_SIZE}" -lt "${IMAGE_SIZE}" ]; then
  >&2 echo "Target device is too small."
  exit 15
fi

DEVICE_REMOVABLE=$(lsblk "${TARGET_DEVICE}" -ndo RM)
if [ "${DEVICE_REMOVABLE}" != " 1" ]; then
  >&2 echo "Target device is not removable."
  exit 16
fi

DEVICE_MOUNTPOINT=$(lsblk "${TARGET_DEVICE}" -no MOUNTPOINT)
if [ "${DEVICE_MOUNTPOINT}" != "" ]; then
  >&2 echo "Target device is mounted."
  exit 17
fi

# Override the partition table 
# located in the MBR sector aka the first 512 bytes 
dd if=/dev/zero of=${TARGET_DEVICE} bs=512 count=1 || {
    echo "Failed to override the partition table"
    exit 19
}

# new msdos partition table + single partition
# Type 83 is the linux partition data
# More: https://www.system-rescue.org/disk-partitioning/Partitions-attributes/
echo 'type=83' | sfdisk ${TARGET_DEVICE} || {
    echo "Failed to write a new MSDOS partition table or a new partition"
    exit 20
}

mkfs.ext4 ${TARGET_DEVICE}1 || {
    echo "Failed to format the partition as ext4"
    exit 21
}


dd if="${SOURCE_IMAGE}" of="${TARGET_DEVICE}" status=progress bs=1M oflag=sync
if [ $? -ne 0 ]; then
  >&2 echo "Could not transfer image to device."
  exit 18
fi

echo "Flashing ${SOURCE_IMAGE} to ${TARGET_DEVICE} is done."
exit 0